### ISSUE TITLE
problem in ApplicationLoader class

### ISSUE THREAD

**Issue by CoderoidAcademy** [TelePlusDev/TelePlus-Android#4]
Hi, i have a problem to running app in org/telegram/messenger/ApplicationLoader.java:
No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean)

full bug is here:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: in.teleplus, PID: 13495
    java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z)
        at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
        at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:157)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6097)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Application terminated.

how i fix it?

**Comment by CoderoidAcademy** [comment]
fix it, just for this i using ndk16

**Comment by cdthy** [comment]
> fix it, just for this i using ndk16
hi  even if i using ndk 16 , this problem still exists 
my config is 
ndk.dir=D\:\\sdk\\android-ndk-16
